version: '3.5'

networks:
  gik_frontend:
    driver: bridge
  gik_backend:
    driver: bridge
    internal: true
    
secrets:
#  MYSQL_USER:
#    file: ./.MYSQL_USER
#  MYSQL_PASSWORD:
#    file: ./.MYSQL_PASSWORD
  MYSQL_ROOT_PASSWORD:
    file: ./.MYSQL_ROOT_PASSWORD

services:

  mysql-server:
    image: mysql:5.6
    restart: unless-stopped
    command:
      - mysqld
      - --character-set-server=utf8
      - --collation-server=utf8_bin
      - --default-authentication-plugin=mysql_native_password
   #   - --require-secure-transport
   #   - --ssl-ca=/run/secrets/root-ca.pem
   #   - --ssl-cert=/run/secrets/server-cert.pem
   #   - --ssl-key=/run/secrets/server-key.pem
    volumes:
      - ./zbx_env/var/lib/mysql:/var/lib/mysql:rw
    ports:
      - 3336:3306
   # env_file:
   #   - .env_db_mysql
    secrets:
  #    - MYSQL_USER
  #    - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
  #   - server-key.pem
  #   - server-cert.pem
  #   - root-ca.pem
    stop_grace_period: 1m
    networks:
      gik_frontend:
      gik_backend:
        aliases:
          - mysql-server
          - gik-database
          - mysql-database

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      gik_frontend:
      gik_backend:
      